# Analysis Options for Indoor Navigation Project

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Error rules
    avoid_print: false
    avoid_relative_lib_imports: true
    avoid_types_as_parameter_names: true

    # Style rules
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_single_quotes: true

    # Pub rules
    sort_pub_dependencies: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
